#ifndef HID_ELGATO_STREAMDECKPLUS_H_FILE
#define HID_ELGATO_STREAMDECKPLUS_H_FILE

#ifndef USB_VENDOR_ID_ELGATO
#define USB_VENDOR_ID_ELGATO 0x0fd9
#endif

#ifndef USB_DEVICE_ID_ELGATO_STREAMDECKPLUS
#define USB_DEVICE_ID_ELGATO_STREAMDECKPLUS 0x0084
#endif

#endif
